namespace DockYarp.Docker.Labels;

using System;
using System.Collections.Generic;

using YamlDotNet.Core;
using YamlDotNet.Serialization;
using YamlDotNet.Serialization.ObjectFactories;
using YamlDotNet.Serialization.TypeInspectors;
using YamlDotNet.Serialization.TypeResolvers;

/// <summary>Hand-written, AOT/trim-safe deserialization context for <see cref="MultiportParser.PathSpec"/>
/// and the dictionary shapes it is nested in (<c>Dictionary&lt;string, Dictionary&lt;string, PathSpec&gt;&gt;</c>).</summary>
/// <remarks>
/// Not generated by <c>Vecc.YamlDotNet.Analyzers.StaticGenerator</c> — two distinct, confirmed-live bugs in
/// that generator (18.1.0, the current release) rule it out for this shape: (1) a <see cref="StaticContext"/>
/// must be a top-level class, not nested, or the generator silently attaches to nothing and every
/// <see cref="StaticContext"/> method throws <see cref="NotImplementedException"/> at runtime — see
/// <see href="https://github.com/aaubry/YamlDotNet/issues/1124">a community report of exactly this
/// failure</see>; (2) even fixed as a top-level class, the generator crashes
/// (<c>IndexOutOfRangeException</c> in its <c>TypeFactoryGenerator</c>) on any explicit
/// <c>[YamlSerializable(typeof(Dictionary&lt;,&gt;))]</c> registration, and without one it compiles but
/// silently fails to deserialize this two-level dictionary shape (confirmed live, both independently and
/// together with fix (1) applied). This hand-written context mirrors the generator's intended output
/// directly against YamlDotNet's own primitives, sidestepping both bugs.
/// </remarks>
internal sealed class MultiportYamlContext : StaticContext
{
    private static readonly Type PathSpecType = typeof(MultiportParser.PathSpec);
    private static readonly Type InnerDictionaryType = typeof(Dictionary<string, MultiportParser.PathSpec>);
    private static readonly Type OuterDictionaryType = typeof(Dictionary<string, Dictionary<string, MultiportParser.PathSpec>>);

    public override bool IsKnownType(Type type) =>
        type == PathSpecType || type == InnerDictionaryType || type == OuterDictionaryType;

    public override ITypeResolver GetTypeResolver() => new StaticTypeResolver();

    public override StaticObjectFactory GetFactory() => new Factory();

    public override ITypeInspector GetTypeInspector() => new Inspector();

    private sealed class Factory : StaticObjectFactory
    {
        public override object Create(Type type)
        {
            if (type == PathSpecType)
            {
                return new MultiportParser.PathSpec();
            }

            if (type == InnerDictionaryType)
            {
                return new Dictionary<string, MultiportParser.PathSpec>(StringComparer.Ordinal);
            }

            if (type == OuterDictionaryType)
            {
                return new Dictionary<string, Dictionary<string, MultiportParser.PathSpec>>(StringComparer.Ordinal);
            }

            throw new NotSupportedException($"Type '{type}' is not known to {nameof(MultiportYamlContext)}.");
        }

        public override Array CreateArray(Type type, int count) =>
            throw new NotSupportedException("No array types are used by VIRTUAL_HOST_MULTIPORTS parsing.");

        public override bool IsDictionary(Type type) => type == InnerDictionaryType || type == OuterDictionaryType;

        public override bool IsArray(Type type) => false;

        public override bool IsList(Type type) => false;

        public override Type GetKeyType(Type type) => typeof(string);

        public override Type GetValueType(Type type) => type == OuterDictionaryType ? InnerDictionaryType : PathSpecType;

        public override void ExecuteOnDeserializing(object value)
        {
        }

        public override void ExecuteOnDeserialized(object value)
        {
        }

        public override void ExecuteOnSerializing(object value)
        {
        }

        public override void ExecuteOnSerialized(object value)
        {
        }
    }

    private sealed class Inspector : TypeInspectorSkeleton
    {
        private static readonly IPropertyDescriptor[] PathSpecProperties =
        [
            new Property<int>("Port", static spec => spec.Port, static (spec, value) => spec.Port = value),
            new Property<string?>("Dest", static spec => spec.Dest, static (spec, value) => spec.Dest = value),
            new Property<string?>("Proto", static spec => spec.Proto, static (spec, value) => spec.Proto = value),
        ];

        public override IEnumerable<IPropertyDescriptor> GetProperties(Type type, object? container) =>
            type == PathSpecType ? PathSpecProperties : [];

        public override string GetEnumName(Type enumType, string name) => name;

        public override string GetEnumValue(object enumValue) => enumValue.ToString()!;

        public override bool HasParseMethod(Type type) => false;

        public override object? Parse(string value, Type expectedType) =>
            throw new NotSupportedException("No types with a custom Parse method are used by VIRTUAL_HOST_MULTIPORTS parsing.");
    }

    /// <summary>A single <see cref="MultiportParser.PathSpec"/> property, read/written via a
    /// compile-time-checked delegate — not reflection.</summary>
    private sealed class Property<TValue>(
        string name, Func<MultiportParser.PathSpec, TValue> getter, Action<MultiportParser.PathSpec, TValue> setter)
        : IPropertyDescriptor
    {
        public string Name => name;

        public Type Type => typeof(TValue);

        public Type? TypeOverride { get; set; }

        public int Order { get; set; }

        public ScalarStyle ScalarStyle { get; set; } = ScalarStyle.Any;

        public bool CanWrite => true;

        public bool Required => false;

        public bool AllowNulls => true;

        public Type? ConverterType => null;

        public T? GetCustomAttribute<T>()
            where T : Attribute => null;

        public IObjectDescriptor Read(object target) =>
            new ObjectDescriptor(getter((MultiportParser.PathSpec)target), typeof(TValue), typeof(TValue));

        public void Write(object target, object? value) => setter((MultiportParser.PathSpec)target, (TValue)value!);
    }
}
