<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DockYarp.AdminApi\DockYarp.AdminApi.csproj" />
    <ProjectReference Include="..\DockYarp.Core\DockYarp.Core.csproj" />
  </ItemGroup>

</Project>
