<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Yarp.ReverseProxy" />
    <PackageReference Include="OpenTelemetry.Extensions.Hosting" />
    <PackageReference Include="OpenTelemetry.Exporter.Prometheus.AspNetCore" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DockYarp.AdminApi\DockYarp.AdminApi.csproj" />
    <ProjectReference Include="..\DockYarp.Core\DockYarp.Core.csproj" />
    <ProjectReference Include="..\DockYarp.Docker\DockYarp.Docker.csproj" />
    <ProjectReference Include="..\DockYarp.Security\DockYarp.Security.csproj" />
    <ProjectReference Include="..\DockYarp.Tls\DockYarp.Tls.csproj" />
  </ItemGroup>

</Project>
