// DockYarp - Bootstrap (no logic yet)
// YARP configuration will be generated by agents according to OpenSpec.

var builder = WebApplication.CreateBuilder(args);

// TODO: Agents will configure YARP, TLS, Docker discovery, middleware, admin API.

var app = builder.Build();
app.Run();
