
# DockYarp.App
Main ASP.NET Core application hosting YARP, Docker discovery, TLS, security, and admin API.

This project intentionally contains no logic yet. All implementation will be generated by agents following OpenSpec.yaml.
